spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orchard_dev
    username: orchard
    password: orchard

orchard:
  qemu:
    vm-storage-path: /tmp/orchard/vms
    enable-kvm: false

logging:
  level:
    dev.orchard: TRACE
