package dev.orchard.gateway.relay;

import dev.orchard.gateway.api.GatewayRoute;
import dev.orchard.gateway.config.GatewayProperties;
import org.apache.sshd.client.SshClient;
import org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier;
import org.apache.sshd.client.session.ClientSession;
import org.apache.sshd.common.AttributeRepository;
import org.apache.sshd.common.config.keys.loader.openssh.OpenSSHKeyPairResourceParser;
import org.apache.sshd.server.command.Command;
import org.apache.sshd.server.command.CommandFactory;
import org.apache.sshd.server.session.ServerSession;
import org.apache.sshd.server.shell.ShellFactory;
import org.apache.sshd.server.subsystem.SubsystemFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPair;
import java.util.concurrent.TimeUnit;

/**
 * Jumphost relay (design spec §Relay Flow). Holds the gateway→seedling SSH
 * client (username {@code cultivator}, internal key) and produces the server
 * shell/exec/subsystem factories that pump each channel through it.
 */
@Component
public class SeedlingRelay {

    private static final Logger log = LoggerFactory.getLogger(SeedlingRelay.class);

    static final String DEFAULT_SSH_USER = "cultivator";

    public static final AttributeRepository.AttributeKey<ClientSession> RELAY_SESSION_KEY = new AttributeRepository.AttributeKey<>();

    private final SshClient sshClient;
    private final GatewayProperties properties;

    private volatile KeyPair internalKey;
    private Path internalKeyPath;

    public SeedlingRelay(SshClient sshClient, GatewayProperties properties) {
        this.sshClient = sshClient;
        this.properties = properties;
    }

    @PostConstruct
    void start() {
        this.internalKeyPath = Path.of(properties.getInternalSshKeyPath());
        this.internalKey = loadInternalKey();
        sshClient.setServerKeyVerifier(AcceptAllServerKeyVerifier.INSTANCE);
        sshClient.start();
        log.info("SeedlingRelay up; internal key from {}", internalKeyPath);
    }

    KeyPair loadInternalKey() {
        Path path = Path.of(properties.getInternalSshKeyPath());
        if (!Files.isReadable(path)) {
            throw new IllegalStateException(
                "Internal SSH key not found at " + path + " (orchard.gateway.internal-ssh-key-path). "
                + "It is generated by the trellis/nursery side (QemuEnvironmentInitializer).");
        }
        try {
            return OpenSSHKeyPairResourceParser.INSTANCE.loadKeyPairs(null, path, null).stream()
                    .findFirst()
                    .orElseThrow(() -> new IllegalStateException("No key in " + path));
        } catch (Exception e) {
            throw new IllegalStateException("Failed to load internal SSH key from " + path, e);
        }
    }

    /** Lazily opens (and caches per server session) the client session to the seedling. */
    public ClientSession relaySession(ServerSession serverSession, GatewayRoute route) throws Exception {
        ClientSession cached = serverSession.getAttribute(RELAY_SESSION_KEY);
        if (cached != null && !cached.isClosed()) {
            return cached;
        }
        ClientSession client = sshClient.connect(DEFAULT_SSH_USER, route.seedlingIp(), route.seedlingPort())
                .verify(10, TimeUnit.SECONDS)
                .getSession();
        client.addPublicKeyIdentity(internalKey);
        client.auth().verify(10, TimeUnit.SECONDS);
        serverSession.setAttribute(RELAY_SESSION_KEY, client);
        serverSession.addCloseFutureListener(future -> client.close(false));
        log.debug("Opened relay session to {}:{}", route.seedlingIp(), route.seedlingPort());
        return client;
    }

    public CommandFactory commandFactory() {
        return (channel, command) -> new RelayCommand(this, RelayCommand.Mode.EXEC, command);
    }

    public ShellFactory shellFactory() {
        return channel -> new RelayCommand(this, RelayCommand.Mode.SHELL, null);
    }

    public SubsystemFactory subsystemFactory() {
        return new SubsystemFactory() {
            @Override
            public String getName() {
                return "sftp";
            }

            @Override
            public Command createSubsystem(org.apache.sshd.server.channel.ChannelSession channel) {
                return new RelayCommand(SeedlingRelay.this, RelayCommand.Mode.SUBSYSTEM, "sftp");
            }
        };
    }
}
