spring:
  datasource:
    url: jdbc:h2:file:${user.home}/.orchard/data/orchard;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7779

orchard:
  security:
    oauth2:
      enabled: true
  dev:
    default-cultivator-id: 11111111-1111-1111-1111-111111111111
